CREATE TABLE IF NOT EXISTS historial (
id INT AUTO_INCREMENT PRIMARY KEY,
ciudad VARCHAR(100) NOT NULL,
temperatura DECIMAL(5,2) NOT NULL,
descripcion VARCHAR(255) NOT NULL,
latitud DOUBLE NOT NULL,
longitud DOUBLE NOT NULL,
fecha DATETIME DEFAULT CURRENT_TIMESTAMP
)
